import React from 'react';
import Head from 'next/head';
import Sidebar from '../sidebar/Sidebar';
import Header from './Header';
import Footer from './Footer';

const Layout = ({ children }) => {
  return (
    <>
      <Head>
        <title>Learning Next</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex h-screen bg-gray-50">
        <Sidebar />
        <div className="flex flex-col flex-1 w-full">
          <Header />
          <main className="h-full overflow-y-auto">
            <div className="container grid px-6 mx-auto">{children}</div>
          </main>
          <Footer />
        </div>
      </div>
    </>
  );
};

export default Layout;
